export const snippetsByCategory = {
    Photography: ['headshot', 'posed', 'candid', 'photorealistic', 'soft focus', 'close up', 'sideview', 'eye contact', 'full depth of field', 'shallow depth of field'],
    'Art Style': ['hyper-realistic', 'still-life', 'textured', 'pastel colours', 'painted light', 'bokeh', 'brushstrokes', 'visible brushstrokes'],
    Landscape: ['pastures', 'serene', 'vistas', 'detailed', 'sun light', 'soft light', 'golden hour light'],
    Environments: ['stunning environment', 'wide-angle', 'aerial view', 'landscape painting', 'aerial photography', 'massive scale', 'street level view', 'landscape', 'panoramic', 'lush vegetation', 'idyllic', 'overhead shot'],
    Detail: ['wallpaper', 'poster', 'sharp focus', 'hyperrealism', 'insanely detailed', 'lush detail', 'filigree', 'intricate', 'crystalline', 'perfectionism', 'max detail', '4k uhd', 'spirals', 'tendrils', 'ornate', 'HQ', 'angelic', 'decorations', 'embellishments', 'masterpiece', 'hard edge', 'breathtaking', 'embroidery'],
    Lighting: ['bloom', 'god rays', 'hard shadows', 'studio lighting', 'soft lighting', 'diffused lighting', 'rim lighting', 'volumetric lighting', 'specular lighting', 'cinematic lighting', 'luminescence', 'translucency', 'subsurface scattering', 'global illumination', 'indirect light', 'radiant light rays', 'bioluminescent details', 'ektachrome', 'glowing', 'shimmering light', 'halo', 'iridescent', 'backlighting', 'caustics'],
    Colors: ['vibrant', 'muted colors', 'vivid color', 'post-processing', 'color grading', 'tone mapping', 'lush', 'low contrast', 'vintage', 'aesthetic', 'psychedelic', 'monochrome'],
    '2D Art': ['digital art', 'digital painting', 'trending on artstation', 'golden ratio', 'evocative', 'award winning', 'shiny', 'smooth', 'surreal', 'divine', 'celestial', 'elegant', 'oil painting', 'soft', 'fascinating', 'fine art', 'official art', 'keyvisual', 'color page', 'halftone', 'character design', 'concept art', 'symmetry', 'pixiv fanbox', 'trending on dribbble', 'precise lineart', 'tarot card'],
    '3D Renders & realism': ['unreal engine', 'octane render', 'bokeh', 'vray', 'houdini render', 'quixel megascans', 'arnold render', '8k uhd', 'ray tracing', 'cgi', 'lumen reflections', 'cgsociety', 'ultra realistic', '100mm', 'film photography', 'dslr', 'cinema4d', 'studio quality', 'film grain', 'analog photo', 'polaroid', 'macro photography', 'overglaze', 'volumetric fog', 'depth of field', 'silhouette', 'motion lines', 'motion blur', 'fisheye', 'ultra-wide angle'],
};
